dbt_action: # Be sure to change this to your dbt project name
  target: "{{ env_var('TARGET_ENV') }}"
  outputs:
    main:
      type: bigquery
      method: service-account
      keyfile: ./creds.json
      project: "{{ env_var('DBT_GOOGLE_PROJECT_DEV') }}"
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET_DEV') }}"
      threads: 32
      timeout_seconds: 300
      priority: interactive
