name: GitHub Pages

on:
  push:
    branches:
      - main 

env:
  TARGET_ENV: main
  DBT_PROFILES_DIR: .
  DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
  DBT_GOOGLE_PROJECT_DEV: ${{ secrets.DBT_GOOGLE_PROJECT_DEV }}
  DBT_GOOGLE_BIGQUERY_DATASET_DEV: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET_DEV }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: deps
        uses: tommybebe/dbt-action@v1.0.1
        with:
          dbt_command: "dbt deps"

      - name: docs generate
        uses: tommybebe/dbt-action@v1.0.1
        with:
          dbt_command: "dbt docs generate"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
